/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.umstek.biometrics.keystrokedynamics;

import javax.swing.JOptionPane;

/**
 *
 * @author SUTIRTHA PAL
 */
public class MouseRegForm extends javax.swing.JFrame {

    /**
     * Creates new form MouseRegForm
     */
    public MouseRegForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keymodel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Pas1 = new javax.swing.JPasswordField();
        Pas2 = new javax.swing.JPasswordField();
        Pas3 = new javax.swing.JPasswordField();
        name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User_name:");

        jLabel3.setText("Password field 2:");

        jLabel4.setText("Password field 3:");

        keymodel.setText("Move forward to train keystroke model");
        keymodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keymodelActionPerformed(evt);
            }
        });

        jLabel5.setText("Training mouse model and password");

        jLabel6.setText("Password field 1:");

        Pas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pas1MouseClicked(evt);
            }
        });
        Pas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pas1ActionPerformed(evt);
            }
        });

        Pas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pas2MouseClicked(evt);
            }
        });

        Pas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pas3MouseClicked(evt);
            }
        });
        Pas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pas3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(keymodel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pas2)
                            .addComponent(Pas3)
                            .addComponent(Pas1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(Pas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Pas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(keymodel)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     String pas1;
    String user;
    int avx;
    private void keymodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keymodelActionPerformed
        // TODO add your handling code here:
        user=name.getText();
         pas1 = new String(Pas1.getPassword());
         avx=(x+x1+x2)/3;
         System.out.println(avx);
        // new LoginForm1(avx);
   // int avy=(y+y1+y2)/3;
        String pas2 = new String(Pas2.getPassword());
        String pas3 = new String(Pas3.getPassword());
        if(pas1.equals(pas2)&&pas2.equals(pas3))
        {
            new RegisterForm(avx).setVisible(true);

            this.dispose();
            
        }
        
        else{
            JOptionPane.showMessageDialog(this, "Password does not match. ");
            Pas1.setText("");
            Pas2.setText("");
            Pas3.setText("");
            
        }
    }//GEN-LAST:event_keymodelActionPerformed
    public String password()
    {
        return pas1;
    }
    public String username()
    {
        return user;
    }
     int x,x1,x2;
    private void Pas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pas1ActionPerformed
        // TODO add your handling code here:
        //String pas1=pass1.
    }//GEN-LAST:event_Pas1ActionPerformed

    private void Pas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pas3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pas3ActionPerformed
    
    private void Pas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pas2MouseClicked
        // TODO add your handling code here:
        x1=evt.getX();
        //y1=evt.getY() ;
        System.out.println(x1);
    }//GEN-LAST:event_Pas2MouseClicked

    private void Pas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pas3MouseClicked
        // TODO add your handling code here:
        x2=evt.getX();
       // y2=evt.getY() ;
        System.out.println(x2);
    }//GEN-LAST:event_Pas3MouseClicked

    private void Pas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pas1MouseClicked
        // TODO add your handling code here:
        x=evt.getX() ;
      // y=evt.getY() ;
       System.out.println(x);
    }//GEN-LAST:event_Pas1MouseClicked
     
   // System.out.println(avx+" "+avy);
   // int avx;
  /* public int xcor(){
       avx=(x+x1+x2)/3;
        System.out.println(avx+" ");
        return avx;
        
    }
   /* public int ycor(){
        int avy=(y+y1+y2)/3;
        System.out.println(avy+" ");
        return avy;
        
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseRegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseRegForm().setVisible(true);
            }
           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pas1;
    private javax.swing.JPasswordField Pas2;
    private javax.swing.JPasswordField Pas3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton keymodel;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
